name: Build and Publish

on:
  push:
    tags:
      - 'test*'

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git describe
        run: |
          git describe --dirty --tags --long

  merge_dev_to_master:
    name: Merge dev -> master
    runs-on: ubuntu-latest
    needs: build_and_publish
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into master
        run: |
          git fetch origin master
          git checkout master
          git merge --ff-only origin/dev
          git push origin master
