name: GitHub CLI Test
on:
  workflow_dispatch:
    inputs:
      a:
        description: "Input A (string)"
        type: string
      b:
        description: "Input B (boolean)"
        type: boolean

permissions:
  actions: write

jobs:
  gh-cli:
    name: Test GitHub CLI
    runs-on: ubuntu-latest
    steps:
      - name: Show gh cli version
        run: gh --version

      - name: Test workflow run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run --repo ${{ github.repository }} test-winget.yml \
            -f release_tag="${{ github.event.inputs.a }}" \
            -f publish=${{ github.event.inputs.b == 'false' }}
