name: Winget Test
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g. "v1.0.0")'
        type: string
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Trim leading v
        id: trim_version
        env:
          TAG: ${{ github.event.inputs.release_tag }}
        run: |
          $VERSION = "$TAG" -replace '^v', ''
          echo "VERSION=$VERSION" >> $env:GITHUB_OUTPUT
      - name: Show version
        env:
          VERSION: ${{ steps.trim_version.outputs.VERSION }}
        run: echo "Version is $env:VERSION"
