name: Winget Test
on:
  workflow_dispatch:
    inputs:
      maa_version:
        description: 'MAA Version (without "v" prefix)'
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish MAA to winget
        env:
          MAA_VERSION: ${{ github.event.inputs.maa_version }}
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: MaaAssistantArknights.MaaAssistantArknights
          version: ${{ env.MAA_VERSION }}
          installers-regex: "-win-"
          max-versions-to-keep: 0
          release-tag: "v${{ env.MAA_VERSION }}"
          fork-user: lucienshawls
          token: ${{ secrets.WINGET_MAA }}
